name: Split Monorepo

on:
    push:
        branches:
            - master
        tags:
            - '*'

jobs:
    split_monorepo:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
              package: [
                'first-package',
                'second-package'
              ]

        steps:
            -   uses: actions/checkout@v2

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                # Uses an action in the root directory
                name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@2.0
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'DalunSelf'
                    split-repository-name: '${{ matrix.package }}'
                    user-name: "GitHub Action"
                    user-email: "action@github.com"
                    branch: "main"

            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                # Uses an action in the root directory
                name: Monorepo Tagged Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@2.0
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'DalunSelf'
                    split-repository-name: '${{ matrix.package }}'
                    user-name: "GitHub Action"
                    user-email: "action@github.com"
                    branch: "main"
