name: monorepo-split

on:
  push:
    tags: '*'

jobs:
  split-monorepo:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - first
          - second
    steps:
      - uses: actions/checkout@v2
      - id: previous-tag
        uses: 'WyriHaximus/github-action-get-previous-tag@master'
      - name: Monorepo Split of ${{ matrix.package }}
        # uses: symplify/monorepo-split-github-action@2.1
        uses: symplify/github-action-monorepo-split@main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          # ref: ${{ github.head_ref }}
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'DalunSelf'
          repository_name: '${{ matrix.package }}'
          branch: main
          tag: ${{ steps.previous-tag.outputs.tag }}
          user_name: 'DalunSelf'
          user_email: 'dalunself@gmail.com'
